services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Supseven\Webauthn\CredentialsService:
    shared: true

  Supseven\Webauthn\WebauthnMfaProvider:
    shared: true
    public: true
    tags:
      - name: mfa.provider
        identifier: 'webauthn'
        title: 'LLL:EXT:webauthn/Resources/Private/Language/locallang.xlf:provider.title'
        description: 'LLL:EXT:webauthn/Resources/Private/Language/locallang.xlf:provider.description'
        icon: 'webauthn'
        defaultProviderAllowed: true
        before: 'totp'
